# -*- coding: utf-8 -*-
from tests import HangulizeTestCase
from hangulize.langs.isl import Icelandic


class IcelandicTestCase(HangulizeTestCase):

    lang = Icelandic()

    def test_people(self):
        self.assert_examples({
            'Agnar Helgason': '아그나르 헬가손',
            'Ágústa Eva Erlendsdóttir': '아우구스타 에바 에를렌스도티르',
            'Albert Guðmundsson': '알베르트 그뷔드뮌손',
            'Ari Þorgilsson': '아리 소르길손',
            'Arnaldur Indriðason': '아르드날뒤르 인드리다손',
            'Árni Magnússon': '아우르드니 마그누손',
            'Árni Sigfússon': '아우르드니 시그푸손',
            'Ásgeir Ásgeirsson': '아우스게이르 아우스게이르손',
            'Ásgeir Helgason': '아우스게이르 헬가손',
            'Ásgeir Sigurvinsson': '아우스게이르 시귀르빈손',
            'Ásmundur Sveinsson': '아우스뮌뒤르 스베인손',
            'Baltasar Kormákur': '발타사르 코르마우퀴르',
            'Björgólfur Guðmundsson': '비외르골뷔르 그뷔드뮌손',
            'Björgólfur Thor Björgólfsson': '비외르골뷔르 소르 비외르골프손',
            'Björgvin Halldórsson': '비외르그빈 하들도르손',
            'Björk Guðmundsdóttir': '비외르크 그뷔드뮌스도티르',
            'Björn Bjarnason': '비외르든 비아르드나손',
            'Björn Hlynur Haraldsson': '비외르든 흘리뉘르 하랄손',
            'Bragi Ólafsson': '브라이이 올라프손',
            'Davíð Oddsson': '다비드 오드손',
            'Davíð Stefánsson': '다비드 스테파운손',
            'Eggert Pálsson': '에게르트 파울손',
            'Eiður Smári Guðjohnsen': '에이뒤르 스마우리 그뷔드요흔센',
            'Einar Bárðarson': '에이나르 바우르다르손',
            'Einar Benediktsson': '에이나르 베네딕츠손',
            'Einar Hákonarson': '에이나르 하우코나르손',
            'Einar Hjörleifsson Kvaran': '에이나르 혜르들레이프손 크바란',
            'Einar Jónsson': '에이나르 욘손',
            'Einar Kárason': '에이나르 카우라손',
            'Einar Már Guðmundsson': '에이나르 마우르 그뷔드뮌손',
            'Einar Örn Benediktsson': '에이나르 외르든 베네딕츠손',
            'Eiríkur rauði': '에이리퀴르 뢰이디',
            'Eiríkur Hauksson': '에이리퀴르 회익손',
            'Emilíana Torrini Davíðsdóttir': '에밀리아나 토리니 다비스도티르',
            'Freydís Eiríksdóttir': '프레이디스 에이릭스도티르',
            'Friðrik Ólafsson': '프리드리크 올라프손',
            'Friðrik Þór Friðriksson': '프리드리크 소르 프리드릭손',
            'Garðar': '가르다르',
            'Geir Hilmar': '게이르 힐마르',
            'Gisli Gudjonsson': '기슬리 그뷔드욘손',
            'Gísli Örn Garðarsson': '기슬리 외르든 가르다르손',
            'Gísli Pálsson': '기슬리 파울손',
            'Guðmundur Arason': '그뷔드뮌뒤르 아라손',
            'Guðmundur Hagalín': '그뷔드뮌뒤르 하갈린',
            'Guðríður Þorbjarnardóttir': '그뷔드리뒤르 소르비아르드나르도티르',
            'Gunnfríður Jónsdóttir': '귄프리뒤르 욘스도티르',
            'Hafdís Huld': '하프디스 휠드',
            'Halldór Ásgrímsson': '하들도르 아우스그림손',
            'Halldór Blöndal': '하들도르 블뢴달',
            'Halldór Kiljan Laxness': '하들도르 킬리안 락스네스',
            'Hallgrímur Helgason': '하들그리뮈르 헬가손',
            'Hannes Hafstein': '한네스 하프스테인',
            'Hannes Hólmsteinn Gissurarson': '한네스 홀름스테이든 기쉬라르손',
            'Hannibal Valdimarsson': '한니발 발디마르손',
            'Haukur Tómasson': '회이퀴르 토마손',
            'Heiðar Helguson': '헤이다르 헬귀손',
            'Helgi Valdimarsson': '헬기 발디마르손',
            'Hermann Hreiðarsson': '헤르만 흐레이다르손',
            'Hilmar Örn Hilmarsson': '힐마르 외르든 힐마르손',
            'Hilmir Snær Guðnason': '힐미르 스나이르 그뷔드나손',
            'Hólmfríður Karlsdóttir': '홀름프리뒤르 카르들스도티르',
            'Hrafn Gunnlaugsson': '흐라픈 귄뢰익손',
            'Hreiðar Már Sigurðsson': '흐레이다르 마우르 시귀르손',
            'Ingólfur Arnarson': '잉골뷔르 아르드나르손',
            'Ísleifur Gissurarson': '이슬레이뷔르 기쉬라르손',
            'Ívar Ingimarsson': '이바르 잉기마르손',
            'Jóhanna Sigurðardóttir': '요한나 시귀르다르도티르',
            'Jóhannes Karl Gudjonsson': '요한네스 카르들 그뷔드욘손',
            'Jóhannes úr Kötlum': '요한네스 우르 쾨틀륌',
            'Jón Ásgeir Jóhannesson': '욘 아우스게이르 요한네손',
            'Jón Baldvin Hannibalsson': '욘 발드빈 한니발손',
            'Jón Kalman Stefánsson': '욘 칼만 스테파운손',
            'Jón Leifs': '욘 레이프스',
            'Jón Loftsson': '욘 로프츠손',
            'Jón Páll Sigmarsson': '욘 파우들 시그마르손',
            'Jón Sigurðsson': '욘 시귀르손',
            'Jón Thoroddsen': '욘 소로드센',
            'Jónas Hallgrímsson': '요나스 하들그림손',
            'Kári Stefánsson': '카우리 스테파운손',
            'Kjartan Ólafsson': '캬르탄 올라프손',
            'Kolbeinn Tumason': '콜베이든 튀마손',
            'Kristín Marja Baldursdóttir': '크리스틴 마리아 발뒤르스도티르',
            'Kristján Eldjárn': '크리스티아운 엘디아우르든',
            'Leifur Eiríksson': '레이뷔르 에이릭손',
            'Linda Pétursdóttir': '린다 피에튀르스도티르',
            'Loftur Sæmundsson': '로프튀르 사이뮌손',
            'Magnús Magnússon': '마그누스 마그누손',
            'Magnús Þorsteinsson': '마그누스 소르스테인손',
            'Magnús Ver Magnússon': '마그누스 베르 마그누손',
            'Margrét Hermanns Auðardóttir': '마르그리에트 헤르만스 외이다르도티르',
            'Margrét Vilhjálmsdóttir': '마르그리에트 빌햐울름스도티르',
            'Markús Örn Antonsson': '마르쿠스 외르든 안톤손',
            'Mugison': '뮈이이손',
            'Nína Dögg Filippusdóttir': '니나 되그 필리퓌스도티르',
            'Ólafur Darri Ólafsson': '올라뷔르 다리 올라프손',
            'Ólafur Egill Ólafsson': '올라뷔르 에이이들 올라프손',
            'Ólafur Jóhann Ólafsson': '올라뷔르 요한 올라프손',
            'Ólafur Ragnar Grímsson': '올라뷔르 라그나르 그림손',
            'Örvar Þóreyjarson Smárason': '외르바르 소레이야르손 스마우라손',
            'Páll Skúlason': '파우들 스쿨라손',
            'Ragnar Bjarnason': '라그나르 비아르드나손',
            'Ragnar Bragason': '라그나르 브라가손',
            'Ragnheiður Gröndal': '라근헤이뒤르 그뢴달',
            'Silvía Nótt': '실비아 노트',
            'Sigurður Helgason': '시귀르뒤르 헬가손',
            'Sigurður Nordal': '시귀르뒤르 노르달',
            'Sigurður Þórarinsson': '시귀르뒤르 소라린손',
            'Sjón': '숀',
            'Snorri Hjartarson': '스노리 햐르타르손',
            'Snorri Sturluson': '스노리 스튀르들뤼손',
            'Steingrímur Hermannsson': '스테잉그리뮈르 헤르만손',
            'Steinunn Sigurðardóttir': '스테이뉜 시귀르다르도티르',
            'Stefán Guðmundur Guðmundsson': '스테파운 그뷔드뮌뒤르 그뷔드뮌손',
            'Sveinn Björnsson': '스베이든 비외르든손',
            'Þóra Magnúsdóttir': '소라 마그누스도티르',
            'Þórarinn Eldjárn': '소라린 엘디아우르든',
            'Þórbergur Þórðarson': '소르베르귀르 소르다르손',
            'Þorfinnur Karlsefni': '소르핀뉘르 카르들세프니',
            'Þorgeirr Þorkelsson Ljósvetningagoði': '소르게이르 소르켈손 리오스베트닝가고디',
            'Thorkell Atlason': '소르케들 아틀라손',
            'Þorsteinn Gylfason': '소르스테이든 길바손',
            'Þorsteinn Pálsson': '소르스테이든 파울손',
            'Þorvaldur Eiríksson': '소르발뒤르 에이릭손',
            'Tinna Gunnlaugsdóttir': '틴나 귄뢰익스도티르',
            'Tómas Guðmundsson': '토마스 그뷔드뮌손',
            'Unnur Birna Vilhjálmsdóttir': '윈뉘르 비르드나 빌햐울름스도티르',
            'Vala Flosadottir': '발라 플로사도티르',
            'Vigdís Finnbogadóttir': '비그디스 핀보가도티르',
            'Vigdís Grímsdóttir': '비그디스 그림스도티르',
            'Viktor Arnar Ingólfsson': '빅토르 아르드나르 잉골프손',
            'Vilhjálmur Árnason': '빌햐울뮈르 아우르드나손',
            'Vilhjálmur Stefánsson': '빌햐울뮈르 스테파운손',
        })

    def test_places(self):
        self.assert_examples({
            'Akranes': '아크라네스',
            'Akureyri': '아퀴레이리',
            'Blöndós': '블뢴도스',
            'Bolungarvík': '볼룽가르비크',
            'Borgafjörður': '보르가피외르뒤르',
            'Borganes': '보르가네스',
            'Dalvík': '달비크',
            'Djúpivogur': '디우피보귀르',
            'Egilsstaðir': '에이일스타디르',
            'Eyjafjallajökull': '에이야피아들라예퀴들',
            'Goðafoss': '고다포스',
            'Grímsey': '그림세이',
            'Grindavík': '그린다비크',
            'Hafnarfjörður': '하프나르피외르뒤르',
            'Höfn í Hornafirði': '회픈 이 호르드나피르디',
            'Hofsjökull': '호프스예퀴들',
            'Hólmavík': '홀마비크',
            'Húsavík': '후사비크',
            'Hvammstangi': '크밤스타웅기',
            'Hvíta': '크비타',
            'Hvolsvöllur': '크볼스뵈들뤼르',
            'Ísafjörður': '이사피외르뒤르',
            'Keflavík': '케플라비크',
            'Kópavogur': '코파보귀르',
            'Lagarfljólt': '라가르플리올트',
            'Langjökull': '라웅그예퀴들',
            'Mosfellsbær': '모스펠스바이르',
            'Mýrdalsjökull': '미르달스예퀴들',
            'Mývatn': '미바튼',
            'Neskaupstaður': '네스쾨이프스타뒤르',
            'Njarðvík': '니아르드비크',
            'Ólafsfjörður': '올라프스피외르뒤르',
            'Ólafsvík': '올라프스비크',
            'Raufarhöfn': '뢰이바르회픈',
            'Reykjanes': '레이캬네스',
            'Reykjavík': '레이캬비크',
            'Sauðárkrókur': '쇠이다우르크로퀴르',
            'Selfoss': '셀포스',
            'Seyðisfjörður': '세이디스피외르뒤르',
            'Siglufjörður': '시글뤼피외르뒤르',
            'Skjálfandafljót': '스캬울반다플리오트',
            'Stykkishólmur': '스티키스홀뮈르',
            'Surtsey': '쉬르트세이',
            'Vatnajökull': '바트나예퀴들',
            'Vík': '비크',
            'Vopnafjörður': '보프나피외르뒤르',
            'Þingvellir': '싱그베들리르',
            'Þjórsá': '시오르사우',
            'Þórisvatn': '소리스바튼',
            'Þorlákshöfn': '소를라욱스회픈',
            'Þórshöfn': '소르스회픈',
        })