# -*- coding: utf-8 -*-
from tests import HangulizeTestCase
from hangulize.langs.lav import Latvian


class LatvianTestCase(HangulizeTestCase):

    lang = Latvian()

    def test_people(self):
        self.assert_examples({
            'Alberts': '알베르츠',
            'Gunārs Astra': '구나르스 아스트라',
            'Helmuts Balderis': '헬무츠 발데리스',
            'Jānis Balodis': '야니스 발로디스',
            'Krišjānis Barons': '크리샤니스 바론스',
            'Mihails Barišņikovs': '미하일스 바리슈니코우스',
            'Vizma Belševica': '비즈마 벨셰비차',
            'Eduards Berklavs': '에두아르츠 베르클라우스',
            'Ernests Blanks': '에르네스츠 블랑크스',
            'Rūdolfs Blaumanis': '루돌프스 블라우마니스',
            'Aleksandrs Čaks': '알렉산드르스 착스',
            'Jānis Čakste': '야니스 착스테',
            'Emīls Dārziņš': '에밀스 다르진슈',
            'Eliass Eliezers Desslers': '엘리아스 엘리에제르스 데슬레르스',
            'Sergejs Eizenšteins': '세르게이스 에이젠슈테인스',
            'Movša Feigins': '모우샤 페이긴스',
            'Elīna Garanča': '엘리나 가란차',
            'Ernests Gulbis': '에르네스츠 굴비스',
            'Uvis Helmanis': '우비스 헬마니스',
            'Artūrs Irbe': '아르투르스 이르베',
            'Kārlis Irbītis': '카를리스 이르비티스',
            'Gatis Jahovičs': '가티스 야호비치',
            'Kaspars Kambala': '카스파르스 캄발라',
            'Aleksandrs Koblencs': '알렉산드르스 코블렌츠',
            'Gustavs Klucis': '구스타우스 클루치스',
            'Ābrams Izāks Kūks': '아브람스 이작스 쿡스',
            'Aleksandrs Kovaļevskis': '알렉산드르스 코발레우스키스',
            'Miķelis Krogzems': '미첼리스 크로그젬스',
            'Juris Kronbergs': '유리스 크론베르크스',
            'Atis Kronvalds': '아티스 크론발츠',
            'Alberts Kviesis': '알베르츠 크비에시스',
            'Aleksandrs Laime': '알렉산드르스 라이메',
            'Nikolajs Loskis': '니콜라이스 로스키스',
            'Jevgēnija Ļisicina': '예우게니야 리시치나',
            'Zigfrīds Anna Meierovics': '직프리츠 안나 메이에로비츠',
            'Evgenijs Millers': '에우게니스 밀레르스',
            'Kārlis Mīlenbahs': '카를리스 밀렌바흐스',
            'Stanislavs Olijars': '스타니슬라우스 올리야르스',
            'Elvīra Ozoliņa': '엘비라 오졸리냐',
            'Vilhelms Ostvalds': '빌헬름스 오스트발츠',
            'Sandis Ozoliņš': '산디스 오졸린슈',
            'Valdemārs Ozoliņš': '발데마르스 오졸린슈',
            'Artis Pabriks': '아르티스 파브릭스',
            'Karlis Padegs': '카를리스 파덱스',
            'Marian Pahars': '마리안 파하르스',
            'Vladimirs Petrovs': '블라디미르스 페트로우스',
            'Andrejs Pumpurs': '안드레이스 품푸르스',
            'Mārtiņš Rubenis': '마르틴슈 루베니스',
            'Juris Rubenis': '유리스 루베니스',
            'Elza Rozenberga': '엘자 로젠베르가',
            'Uļjana Semjonova': '울랴나 세묘노바',
            'Māris Štrombergs': '마리스 슈트롬베르크스',
            'Pēteris Stučka': '페테리스 스투치카',
            'Viktors Ščerbatihs': '빅토르스 슈체르바티흐스',
            'Haralds Silovs': '하랄츠 실로우스',
            'Andris Šķēle': '안드리스 슈첼레',
            'Ernests Štālbergs': '에르네스츠 슈탈베르크스',
            'Guntis Ulmanis': '군티스 울마니스',
            'Kārlis Ulmanis': '카를리스 울마니스',
            'Romāns Vainšteins': '로만스 바인슈테인스',
            'Krišjānis Valdemārs': '크리샤니스 발데마르스',
            'Miķelis Valters': '미첼리스 발테르스',
            'Valdis Valters': '발디스 발테르스',
            'Aleksandrs Vanags': '알렉산드르스 바낙스',
            'Ojārs Vācietis': '오야르스 바치에티스',
            'Eduards Veidenbaums': '에두아르츠 베이덴바움스',
            'Makss Veinreihs': '막스 베인레이흐스',
            'Visvaldis': '비스발디스',
            'Jāzeps Vītols': '야젭스 비톨스',
            'Māris Verpakovskis': '마리스 베르파코우스키스',
            'Aleksandrs Voitkevičs': '알렉산드르스 보이트케비치',
            'Kārlis Zariņš': '카를리스 자린슈',
            'Gustavs Zemgals': '구스타우스 젬갈스',
            'Valdis Zatlers': '발디스 자틀레르스',
            'Imants Ziedonis': '이만츠 지에도니스',
            'Sergejs Žoltoks': '세르게이스 졸톡스',
        })

    def test_places(self):
        self.assert_examples({
            'Daugava': '다우가바',
            'Daugavpils': '다우가우필스',
            'Grobiņa': '그로비냐',
            'Jēkabpils': '예캅필스',
            'Jelgava': '옐가바',
            'Jersika': '예르시카',
            'Jūrmala': '유르말라',
            'Koknese': '코크네세',
            'Kurzeme': '쿠르제메',
            'Latgale': '라트갈레',
            'Latvija': '라트비야',
            'Liepāja': '리에파야',
            'Rēzekne': '레제크네',
            'Rīga': '리가',
            'Valmiera': '발미에라',
            'Ventspils': '벤츠필스',
            'Vidzeme': '비제메',
            'Zemgale': '젬갈레',
        })