# -*- coding: utf-8 -*-
from hangulize import *


class Japanese(Language):
    """For transcribing Japanese."""

    __iso639__ = {1: 'ja', 2: 'jpn', 3: 'jpn'}
    __tmp__ = ''.join((chr(x) + chr(x).upper()) \
                      for x in range(ord('a'), ord('z') + 1))

    notation = Notation([
        ('ア|ァ',    'a'),
        ('イ|ィ',    'i'),
        ('ウ|ゥ',    'u'),
        ('エ|ェ',    'e'),
        ('オ|ォ',    'o'),
        ('カ',       'ka'),
        ('キ',       'ki'),
        ('ク',       'ku'),
        ('ケ',       'ke'),
        ('コ',       'ko'),
        ('ガ',       'ga'),
        ('ギ',       'gi'),
        ('グ',       'gu'),
        ('ゲ',       'ge'),
        ('ゴ',       'go'),
        ('サ',       'sa'),
        ('シ',       'si'),
        ('ス',       'su'),
        ('セ',       'se'),
        ('ソ',       'so'),
        ('ザ',       'za'),
        ('ジ',       'zi'),
        ('ズ',       'zu'),
        ('ゼ',       'ze'),
        ('ゾ',       'zo'),
        ('タ',       'ta'),
        ('チ',       'ci'),
        ('ツ',       'cu'),
        ('テ',       'te'),
        ('ト',       'to'),
        ('ダ',       'da'),
        ('ヂ',       'zi'),
        ('ヅ',       'zu'),
        ('デ',       'de'),
        ('ド',       'do'),
        ('ナ',       'na'),
        ('ニ',       'ni'),
        ('ヌ',       'nu'),
        ('ネ',       'ne'),
        ('ノ',       'no'),
        ('ハ',       'ha'),
        ('ヒ',       'hi'),
        ('フ',       'hu'),
        ('ヘ',       'he'),
        ('ホ',       'ho'),
        ('バ',       'ba'),
        ('ビ',       'bi'),
        ('ブ',       'bu'),
        ('ベ',       'be'),
        ('ボ',       'bo'),
        ('パ',       'pa'),
        ('ピ',       'pi'),
        ('プ',       'pu'),
        ('ペ',       'pe'),
        ('ポ',       'po'),
        ('マ',       'ma'),
        ('ミ',       'mi'),
        ('ム',       'mu'),
        ('メ',       'me'),
        ('モ',       'mo'),
        ('ヤ',       'ya'),
        ('ユ',       'yu'),
        ('ヨ',       'yo'),
        ('ャ',       'ja'),
        ('ュ',       'ju'),
        ('ョ',       'jo'),
        ('ラ',       'la'),
        ('リ',       'li'),
        ('ル',       'lu'),
        ('レ',       'le'),
        ('ロ',       'lo'),
        ('ワ',       'wa'),
        ('ヲ',       'o'),
        ('ン',       'N'),
        ('ッ',       'T'),
        ('^k',        'g'),
        ('^t',        'd'),
        ('^c{a|i}',   'z'),
        ('{(y|j)o}o', 'O'),
        ('{a}a',      None),
        ('{i}i',      None),
        ('{u|o}u',    None),
        ('{e}e',      None),
        ('{o}o',      None),
        ('O',         'o'),
        ('{c|z}ija',  'a'),
        ('{c|z}iju',  Jungseong(U)),
        ('{c|z}ijo',  'o'),
        ('cu',        Choseong(SS), Jungseong(EU)),
        ('wa',        Jungseong(WA)),
        ('{s|z}u',    Jungseong(EU)),
        ('k',         Choseong(K)),
        ('g',         Choseong(G)),
        ('s',         Choseong(S)),
        ('z',         Choseong(J)),
        ('t',         Choseong(T)),
        ('c',         Choseong(C)),
        ('d',         Choseong(D)),
        ('n',         Choseong(N)),
        ('h',         Choseong(H)),
        ('b',         Choseong(B)),
        ('p',         Choseong(P)),
        ('m',         Choseong(M)),
        ('l',         Choseong(L)),
        ('ya',        Jungseong(YA)),
        ('yu',        Jungseong(YU)),
        ('yo',        Jungseong(YO)),
        ('ija',       Jungseong(YA)),
        ('iju',       Jungseong(YU)),
        ('ijo',       Jungseong(YO)),
        ('a',         Jungseong(A)),
        ('i',         Jungseong(I)),
        ('u',         Jungseong(U)),
        ('e',         Jungseong(E)),
        ('o',         Jungseong(O)),
        ('N',         Jongseong(N)),
        ('T',         Jongseong(S))
    ])

    def normalize(self, string):
        def hiragana_to_katakana(c):
            code = ord(c)
            if code not in range(0x3040, 0x309f + 1):
                return c
            return chr(code + 96)
        return ''.join(map(hiragana_to_katakana, string))


__lang__ = Japanese
