# -*- coding: utf-8 -*-
from hangulize import *


class Azerbaijani(Language):
    """For transcribing Azerbaijani."""

    __iso639__ = {1: 'az', 2: 'aze', 3: 'aze'}
    __tmp__ = ',;'

    vowels = 'aAeIioOuU'
    cs = 'bcCdfgGhjklmnNpqrsStvxz'
    vl = 'CfhkKpsStx'
    notation = Notation([
        ('-', '/'),
        ('ə', 'A'),
        ('ç', 'C'),
        ('ğ', 'G'),
        ('ı', 'I'),
        ('ö', 'O'),
        ('ş', 'S'),
        ('ü', 'U'),
        ('^y{@}', 'Y'),
        ('iyy', 'iy'),
        ('yy', 'iy'),
        ('{@}y{@}', 'Y'),
        ('iy', 'i'),
        ('y', 'i'),
        ('rl', 'l'),
        ('{p|t|k}h', None),
        ('w', 'v'),
        ('bb', 'b'),
        ('cc', 'c'),
        ('CC', 'C'),
        ('dd', 'd'),
        ('dc', 'c'),
        ('ff', 'f'),
        ('gg', 'g'),
        ('GG', 'G'),
        ('hh', 'h'),
        ('jj', 'j'),
        ('kk', 'k'),
        ('ll', 'l'),
        ('mm', 'm,m'),
        ('nn', 'n,n'),
        ('pp', 'p'),
        ('qq', 'q'),
        ('rr', 'r'),
        ('ss', 's'),
        ('SS', 'S'),
        ('tt', 't'),
        ('tC', 'C'),
        ('vv', 'v'),
        ('xx', 'x'),
        ('zz', 'z'),
        ('aa', 'a'),
        ('AA', 'A'),
        ('ee', 'e'),
        ('ii', 'i'),
        ('II', 'I'),
        ('oo', 'o'),
        ('OO', 'O'),
        ('uu', 'u'),
        ('UU', 'U'),
        ('b{<vl>}', 'p'),
        ('b$', 'p'),
        ('c{<vl>}', 'C'),
        ('c$', 'C'),
        ('d{<vl>}', 't'),
        ('d$', 't'),
        ('g{<vl>}', 'k'),
        ('g$', 'k'),
        ('G{<vl>}', 'x'),
        ('G$', 'x'),
        ('j{<vl>}', 'S'),
        ('j$', 'S'),
        ('q{<vl>}', 'Q'),
        ('q$', 'Q'),
        ('v{<vl>}', 'f'),
        ('v$', 'f'),
        ('z{<vl>}', 's'),
        ('z$', 's'),
        ('{@}k{<vl>}', 'k,'),
        ('{@}p{<vl>}', 'p,'),
        ('{@}Q{<vl>}', 'k,'),
        ('c{<cs>}', 'ci'),
        ('c$', 'ci'),
        ('C{<cs>}', 'Ci'),
        ('C$', 'Ci'),
        ('j{<cs>}', 'ju'),
        ('j$', 'ju'),
        ('S{@}', 'sY'),
        ('S', 'sYu'),
        ('^l', 'l;'),
        ('^m', 'm;'),
        ('^n', 'n;'),
        ('n{G|q|Q|x}', 'N'),
        ('l$', 'l,'),
        ('m$', 'm,'),
        ('n$', 'n,'),
        ('l{@|m,|n,|N}', 'l;'),
        ('{,}l', 'l;'),
        ('m{@}', 'm;'),
        ('n{@}', 'n;'),
        ('l', 'l,'),
        ('m', 'm,'),
        ('n', 'n,'),
        (',,', ','),
        (',;', None),
        (',l,', 'l,'),
        (',m,', 'm,'),
        (',n,', 'n,'),
        ('l{m;|n;}', 'l,'),
        (';', None),
        ('b', Choseong(B)),
        ('c', Choseong(J)),
        ('C', Choseong(C)),
        ('d', Choseong(D)),
        ('f', Choseong(P)),
        ('g', Choseong(G)),
        ('G', Choseong(G)),
        ('h', Choseong(H)),
        ('j', Choseong(J)),
        ('k,', Jongseong(G)),
        ('k', Choseong(K)),
        ('^l', Choseong(L)),
        ('{,}l', Choseong(L)),
        ('l,', Jongseong(L)),
        ('l', Jongseong(L), Choseong(L)),
        ('m,', Jongseong(M)),
        ('m', Choseong(M)),
        ('n,', Jongseong(N)),
        ('n', Choseong(N)),
        ('N', Jongseong(NG)),
        ('p,', Jongseong(B)),
        ('p', Choseong(P)),
        ('q', Choseong(G)),
        ('Q', Choseong(K)),
        ('r', Choseong(L)),
        ('s', Choseong(S)),
        ('t', Choseong(T)),
        ('v', Choseong(B)),
        ('x', Choseong(H)),
        ('z', Choseong(J)),
        ('Ya', Jungseong(YA)),
        ('YA', Jungseong(YE)),
        ('Ye', Jungseong(YE)),
        ('YI', Jungseong(I), Jungseong(EU)),
        ('Yi', Jungseong(I)),
        ('Yo', Jungseong(YO)),
        ('YO', Jungseong(OE)),
        ('Yu', Jungseong(YU)),
        ('YU', Jungseong(WI)),
        ('a', Jungseong(A)),
        ('A', Jungseong(E)),
        ('e', Jungseong(E)),
        ('I', Jungseong(EU)),
        ('i', Jungseong(I)),
        ('o', Jungseong(O)),
        ('O', Jungseong(OE)),
        ('u', Jungseong(U)),
        ('U', Jungseong(WI)),
    ])

    def normalize(self, string):
        return normalize_roman(string, {
            'Ə': 'ə', 'Ç': 'ç', 'Ğ': 'ğ', 'I': 'ı', 'İ': 'i',
            'Ö': 'ö', 'Ş': 'ş', 'Ü': 'ü', 'А': 'a', 'а': 'a',
            'Ә': 'ə', 'ә': 'ə', 'Б': 'b', 'б': 'b', 'Ҹ': 'c',
            'ҹ': 'c', 'Ч': 'ç', 'ч': 'ç', 'Д': 'd', 'д': 'd',
            'Е': 'e', 'е': 'e', 'Ф': 'f', 'ф': 'f', 'Ҝ': 'g',
            'ҝ': 'g', 'Ғ': 'ğ', 'ғ': 'ğ', 'Һ': 'h', 'һ': 'h',
            'Х': 'x', 'х': 'x', 'Ы': 'ı', 'ы': 'ı', 'И': 'i',
            'и': 'i', 'Ж': 'j', 'ж': 'j', 'К': 'k', 'к': 'k',
            'Г': 'q', 'г': 'q', 'Л': 'l', 'л': 'l', 'М': 'm',
            'м': 'm', 'Н': 'n', 'н': 'n', 'О': 'o', 'о': 'o',
            'Ө': 'ö', 'ө': 'ö', 'П': 'p', 'п': 'p', 'Р': 'r',
            'р': 'r', 'С': 's', 'с': 's', 'Ш': 'ş', 'ш': 'ş',
            'Т': 't', 'т': 't', 'У': 'u', 'у': 'u', 'Ү': 'ü',
            'ү': 'ü', 'В': 'v', 'в': 'v', 'Ј': 'y', 'ј': 'y',
            'З': 'z', 'з': 'z'
        })


__lang__ = Azerbaijani
