# -*- coding: utf-8 -*-
from hangulize import *


class NarrowGeorgian(Language):
    """For transcribing Georgian (narrow transcription).
    The lenis, fortis, and aspirated series of stops and affricates of Korean
    are all employed. The Georgian grapheme ვ is taken to be /w/ after an
    obstruent and before a vowel, to be /f/ after a vowel and before a
    voiceless stop or affricate, and to be /v/ in all other cases."""

    __iso639__ = {1: 'ka', 2: 'geo', 3: 'kat'}
    __tmp__ = ',;'

    vowels = 'აეიოუ'
    cs = 'ბგდვზთკლმნპჟრსტფქღყშჩცძწჭხჯჰV'
    vl = 'თკპტფქყჩცწჭ'
    ob = 'ბგდვზთკპჟსტფქღყშჩცძწჭხჯჰ'
    notation = Notation([
        ('ჱ', 'ეჲ'),
        ('ჲ', 'ი'),
        ('უჳ', 'უ'),
        ('ჳ', 'უ'),
        ('ჴ', 'ხ'),
        ('ჵ', 'ო'),
        ('ჶ', 'ფ'),
        ('{@}ვ{<vl>}', 'ჶ'),
        ('ვ$', 'ჶ'),
        ('ბბ', 'ბ'),
        ('გგ', 'გ'),
        ('დდ', 'დ'),
        ('ვვ', 'ვ'),
        ('ზზ', 'ზ'),
        ('თთ', 'თ'),
        ('კკ', 'კ'),
        ('ლლ', 'ლ'),
        ('მმ', 'მ,მ'),
        ('ნნ', 'ნ,ნ'),
        ('პპ', 'პ'),
        ('ჟჟ', 'ჟ'),
        ('რრ', 'რ'),
        ('სს', 'ს'),
        ('ტტ', 'ტ'),
        ('ფფ', 'ფ'),
        ('ქქ', 'ქ'),
        ('ღღ', 'ღ'),
        ('ყყ', 'ყ'),
        ('შშ', 'შ'),
        ('ხხ', 'ხ'),
        ('ჰჰ', 'ჰ'),
        ('დ{ძ|ჯ}', None),
        ('თ{ჩ|ც}', None),
        ('ტ{წ|ჭ}', None),
        ('დჟ', 'ჯ'),
        ('თშ', 'ჩ'),
        ('ტშ', 'ჭ'),
        ('დზ', 'ძ'),
        ('თს', 'ც'),
        ('ტს', 'წ'),
        ('{<ob>}ვ{ა|ე|ი}', 'V'),
        ('ჟ{<cs>}', 'ჟუ'),
        ('ჟ$', 'ჟუ'),
        ('შ{<cs>}', 'შუ'),
        ('შ$', 'ში'),
        ('ჩ{V}', 'ჩუ'),
        ('ჩ{<cs>}', 'ჩი'),
        ('ჩ$', 'ჩი'),
        ('ძ{V}', 'ძუ'),
        ('ძ{<cs>}', 'ძი'),
        ('ძ$', 'ძი'),
        ('ჭ{V}', 'ჭუ'),
        ('ჭ{<cs>}', 'ჭი'),
        ('ჭ$', 'ძი'),
        ('^ლ', 'ლ;'),
        ('^მ$', 'მ;'),
        ('^ნ', 'ნ;'),
        ('ლ$', 'ლ,'),
        ('მ$', 'მ,'),
        ('ნ$', 'ნ,'),
        ('ლ{@|მ,|ნ,}', 'ლ;'),
        ('{,}ლ', 'ლ;'),
        ('მ{@}', 'მ;'),
        ('ნ{@}', 'ნ;'),
        ('ლ', 'ლ,'),
        ('მ', 'მ,'),
        ('ნ', 'ნ,'),
        (',,', ','),
        (',;', None),
        (',ლ,', 'ლ,'),
        (',მ,', 'მ,'),
        (',ნ,', 'ნ,'),
        ('ლ{მნ}', 'ლ,'),
        (';', None),
        ('აა', 'ა'),
        ('ეე', 'ე'),
        ('იი', 'ი'),
        ('ოო', 'ო'),
        ('უუ', 'უ'),
        ('ბ', Choseong(B)),
        ('გ', Choseong(G)),
        ('დ', Choseong(D)),
        ('ვ', Choseong(B)),
        ('ზ', Choseong(J)),
        ('თ', Choseong(T)),
        ('კ', Choseong(GG)),
        ('^ლ', Choseong(L)),
        ('{,}ლ', Choseong(L)),
        ('ლ,', Jongseong(L)),
        ('ლ', Jongseong(L), Choseong(L)),
        ('მ,', Jongseong(M)),
        ('მ', Choseong(M)),
        ('ნ,', Jongseong(N)),
        ('ნ', Choseong(N)),
        ('პ', Choseong(BB)),
        ('ჟ', Choseong(J)),
        ('რ', Choseong(L)),
        ('ს', Choseong(S)),
        ('ტ', Choseong(DD)),
        ('ფ', Choseong(P)),
        ('ქ', Choseong(K)),
        ('ღ', Choseong(G)),
        ('ყ', Choseong(GG)),
        ('ჩ', Choseong(C)),
        ('ც', Choseong(C)),
        ('ძ', Choseong(J)),
        ('წ', Choseong(JJ)),
        ('ჭ', Choseong(JJ)),
        ('ხ', Choseong(H)),
        ('ჯ', Choseong(J)),
        ('ჰ', Choseong(H)),
        ('ჶ', Choseong(P)),
        ('ჸ', Choseong(NG)),
        ('შა', Choseong(S), Jungseong(YA)),
        ('შე', Choseong(S), Jungseong(YE)),
        ('ში', Choseong(S), Jungseong(I)),
        ('შო', Choseong(S), Jungseong(YO)),
        ('შუ', Choseong(S), Jungseong(YU)),
        ('შჷ', Choseong(S), Jungseong(YEO)),
        ('Vა', Choseong(NG), Jungseong(WA)),
        ('Vე', Choseong(NG), Jungseong(WE)),
        ('Vი', Choseong(NG), Jungseong(WI)),
        ('ა', Jungseong(A)),
        ('ე', Jungseong(E)),
        ('ი', Jungseong(I)),
        ('ო', Jungseong(O)),
        ('უ', Jungseong(U)),
        ('ჷ', Jungseong(EO)),
    ])

    def normalize(self, string):
        return normalize_roman(string, {
            'Ⴀ': 'ა', 'ⴀ': 'ა', 'Ⴁ': 'ბ', 'ⴁ': 'ბ', 'Ⴂ': 'გ',
            'ⴂ': 'გ', 'Ⴃ': 'დ', 'ⴃ': 'დ', 'Ⴄ': 'ე', 'ⴄ': 'ე',
            'Ⴅ': 'ვ', 'ⴅ': 'ვ', 'Ⴆ': 'ზ', 'ⴆ': 'ზ', 'Ⴡ': 'ჱ',
            'ⴡ': 'ჱ', 'Ⴇ': 'თ', 'ⴇ': 'თ', 'Ⴈ': 'ი', 'ⴈ': 'ი',
            'Ⴉ': 'კ', 'ⴉ': 'კ', 'Ⴊ': 'ლ', 'ⴊ': 'ლ', 'Ⴋ': 'მ',
            'ⴋ': 'მ', 'Ⴌ': 'ნ', 'ⴌ': 'ნ', 'Ⴢ': 'ჲ', 'ⴢ': 'ჲ',
            'Ⴍ': 'ო', 'ⴍ': 'ო', 'Ⴎ': 'პ', 'ⴎ': 'პ', 'Ⴏ': 'ჟ',
            'ⴏ': 'ჟ', 'Ⴐ': 'რ', 'ⴐ': 'რ', 'Ⴑ': 'ს', 'ⴑ': 'ს',
            'Ⴒ': 'ტ', 'ⴒ': 'ტ', 'Ⴣ': 'ჳ', 'ⴣ': 'ჳ', 'Ⴍ': 'უ',
            'ⴍ': 'უ', 'Ⴔ': 'ფ', 'ⴔ': 'ფ', 'Ⴕ': 'ქ', 'ⴕ': 'ქ',
            'Ⴖ': 'ღ', 'ⴖ': 'ღ', 'Ⴗ': 'ყ', 'ⴗ': 'ყ', 'Ⴘ': 'შ',
            'ⴘ': 'შ', 'Ⴙ': 'ჩ', 'ⴙ': 'ჩ', 'Ⴚ': 'ც', 'ⴚ': 'ც',
            'Ⴛ': 'ძ', 'ⴛ': 'ძ', 'Ⴜ': 'წ', 'ⴜ': 'წ', 'Ⴝ': 'ჭ',
            'ⴝ': 'ჭ', 'Ⴞ': 'ხ', 'ⴞ': 'ხ', 'Ⴤ': 'ჴ', 'ⴤ': 'ჴ',
            'Ⴟ': 'ჯ', 'ⴟ': 'ჯ', 'Ⴠ': 'ჰ', 'ⴠ': 'ჰ', 'Ⴥ': 'ჵ',
            'ⴥ': 'ჵ'
        })


__lang__ = NarrowGeorgian
